[package]
name = "name-popularity"
version = "0.1.1"
authors = ["Techcable <Techcable@techcable.net>"]

[dependencies]
# Serde
serde = "^1"
serde_derive = "^1"
# Rocket
rocket = "^0.4.4"
# Better synchronization primitives
parking_lot = { version = "^0.5.5", features = ["nightly"] }

[dependencies.rocket_contrib]
version = "^0.4.4"
default-features = false
features = ["json"]
