[package]
name = "name-popularity"
version = "0.1.2"
authors = ["Techcable <Techcable@techcable.net>"]

[dependencies]
# Serde
serde = "1"
serde_derive = "1"
# Rocket
rocket = "0.4.5"
# Better synchronization primitives
parking_lot = { version = "^0.11", features = ["nightly"] }

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json"]

[profile.release]
# Thinlto
lto="thin"
